version: '3.9'

services:
  postgres:
    build: ./containers/postgres
    ports:
      - '127.0.0.1:5432:5432'
    env_file:
      - .env
    volumes:
      - ./postgres/pg:/var/lib/postgresql/data


  node-capygram:
    build: ./containers/node-capygram
    ports:
      - '127.0.0.1:8080:8080'
    volumes:
      - ./app:/app
    env_file:
      - .env
    depends_on:
      - postgres
    restart: always
